#ifndef BOOT_GDT_H
#define BOOT_GDT_H

// https://wiki.osdev.org/Global_Descriptor_Table

#define GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE 40
#define GDT_SEGMENT_DESCRIPTOR_BASE_FLAGS_BYTE 52

#define GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_A (GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE + 0)
#define GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_RW (GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE + 1)
#define GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_DC (GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE + 2)
#define GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_E (GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE + 3)
#define GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_S (GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE + 4)
#define GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_DPL (GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE + 5)
#define GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_P (GDT_SEGMENT_DESCRIPTOR_BASE_ACCESS_BYTE + 7)

#define GDT_SEGMENT_DESCRIPTOR_ACCESS_A (1 << GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_A)
#define GDT_SEGMENT_DESCRIPTOR_ACCESS_RW (1 << GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_RW)
#define GDT_SEGMENT_DESCRIPTOR_ACCESS_DC (1 << GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_DC)
#define GDT_SEGMENT_DESCRIPTOR_ACCESS_E (1 << GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_E)
#define GDT_SEGMENT_DESCRIPTOR_ACCESS_S (1 << GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_S)
#define GDT_SEGMENT_DESCRIPTOR_ACCESS_P (1 << GDT_SEGMENT_DESCRIPTOR_BIT_ACCESS_P)

#define GDT_SEGMENT_DESCRIPTOR_BIT_FLAGS_L (GDT_SEGMENT_DESCRIPTOR_BASE_FLAGS_BYTE + 1)
#define GDT_SEGMENT_DESCRIPTOR_BIT_FLAGS_DB (GDT_SEGMENT_DESCRIPTOR_BASE_FLAGS_BYTE + 2)
#define GDT_SEGMENT_DESCRIPTOR_BIT_FLAGS_G (GDT_SEGMENT_DESCRIPTOR_BASE_FLAGS_BYTE + 3)

#define GDT_SEGMENT_DESCRIPTOR_FLAGS_L (1 << GDT_SEGMENT_DESCRIPTOR_BIT_FLAGS_L)
#define GDT_SEGMENT_DESCRIPTOR_FLAGS_DB (1 << GDT_SEGMENT_DESCRIPTOR_BIT_FLAGS_DB)
#define GDT_SEGMENT_DESCRIPTOR_FLAGS_G (1 << GDT_SEGMENT_DESCRIPTOR_BIT_FLAGS_G)

#endif